language: en-US
reviews:
  profile: assertive
  request_changes_workflow: false
  high_level_summary: true
  review_status: true
  commit_status: true

  poem: false
  collapse_walkthrough: true
  sequence_diagrams: true
  changed_files_summary: true

  path_filters:
    - '!**/node_modules/**'
    - '!**/*.lock'
    - '!.next/**'
    - 'src/**'

  path_instructions:
    - path: '**/*.ts'
      instructions: Ensure strict TypeScript practices and proper type definitions. Prefer interfaces over types.
    - path: '**/*.tsx'
      instructions: Follow React best practices. Ensure proper component typing and use of React.FC for functional components.

  auto_review:
    enabled: true
    auto_incremental_review: true
    ignore_title_keywords: [wip, draft]
    drafts: false
    base_branches: [master, develop]

  tools:
    biome:
      enabled: true
    eslint:
      enabled: true
    markdownlint:
      enabled: true
    gitleaks:
      enabled: true

knowledge_base:
  learnings:
    scope: auto 
  pull_requests:
    scope: auto
